version: "3"

volumes:
  postgres_data:
  flask: {}

services:
  postgres:
    image: postgres:16.0-alpine3.18
    container_name: postgres
    env_file: .env
    ports:
      - "8001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flask:
    build: .
    image: flask_app
    container_name: flask
    restart: always
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "8000:8000"
    volumes: [".:/app"]
