version: "3"

volumes:
  postgres: {}
  flask: {}

services:
  postgres:
    image: postgres
    container_name: postgres
    env_file: .env
    ports:
      - "8001:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/pgdata

  flask:
    build: .
    container_name: flask
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "8000:8000"
    volumes: [".:/app"]
