name: pre-commit
run-name: ${{ github.actor }} is running the pre-commit pipeline  🚀
on: [push]
jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files
